#!/bin/bash
#GENERATE JUST OBJECT MAIN FILE
$CROSS_COMPILER -c -o main.o main.c
#GENERATE OBJECT FILE FROM PROJECT LIRARIES WITH INDEPENDENT POSITION 
$CROSS_COMPILER -c -fPIC -o spi_driver.o spi_driver.c
$CROSS_COMPILER -c -fPIC -o hs12864.o hs12864.c 
#gcc -c -fPIC -o gpio.o gpio.c
#GENERATE DYNAMIC LIBRARY WITH OBJECTS SOURCES SHARED
$CROSS_COMPILER -o dynlib.so -shared gpio.o hs12864.o spi_driver.o
#GENERATE MAIN EXECUTABLE FROM DYNAMIC LIBRARY
$CROSS_COMPILER -o main main.o dynlib.so
#GIVE PATH OF DYNAMIC LIBRARY TO SYSTEM
export LD_LIBRARY_PATH=.
